name: Build and Deploy

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  DB_USERNAME: ${{secrets.DB_USERNAME}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  QUERY_LIMIT: ${{secrets.QUERY_LIMIT}}
  USER_LIMIT: ${{secrets.USER_LIMIT}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull git repo
        uses: actions/checkout@v3

      - name: Install python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install all dependencies
        run: pip install -r requirements.txt

  deploy:
    # Reference: https://farhan-tanvir.medium.com/ci-cd-from-github-to-aws-ec2-using-github-action-e18b621c0507
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.AWS_PUBLIC_DNS  }}
          USER_NAME : ${{ secrets.AWS_USERNAME  }}
        
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            # Inside EC2
            cd /home/ubuntu/application/ &&
            source venv/bin/activate &&
            cd src &&
            git pull origin main &&
            pip install -r requirements.txt &&
            sudo systemctl restart pud.service
          '
